coverage:
  round: nearest
  ignore:
    - ackhandler/packet_linkedlist.go
    - h2quic/gzipreader.go
    - h2quic/response.go
    - internal2/utils/byteinterval_linkedlist.go
    - internal2/utils/packetinterval_linkedlist.go
  status:
    project:
      default:
        threshold: 0.5
    patch: false
